x=30
y=25
z=20

print (x<y)  
print (x>y) 

print (x==y)  
print (x!=y)

print (x<=y)  
print (x>=y)

print (x<y<z)
print (x>y>z)


A = int(input("enter the value of A:"))
B = int(input("enter the value of B:"))  
C = int(input("enter the value of C:"))
D = int(input("enter the value of D:"))


print(A>B<C<D)
print(A<B>C<D)
print(A>B<C>D)
print(A<B>C>D)
print(A==B<C!=D)
print(A!=B>C==D)
print(A==B<C!=D)
print(A!=B>C==D)
print(A==B<=C!=D)
print(A!=B>=C==D)
print(A==B<=C!=D)
print(A!=B>=C==D)
print(A==B>=C!=D)
print(A!=B<=C==D)
print(A==B>=C!=D)
print(A!=B<=C==D)
print(A!=B<=C!=D)
print(A==B>=C==D)
print(A!=B<=C<=D)
print(A==B>=C>=D)
print(A!=B<=C<=D)
print(A==B>=C>=D)
print(A!=B>=C<=D)
print(A==B<=C>=D)
print(A!=B>=C<=D)
print(A==B<=C>=D)
print(A!=B!=C!=D)
print(A==B==C==D)
print(A!=B!=C==D)
print(A==B==C!=D)
print(A!=B==C!=D)
print(A==B!=C==D)
print(A!=B==C==D)
print(A!=B!=C==D)
print(A==B==C!=D)
print(A!=B==C!=D)
print(A==B!=C==D)
print(A!=B!=C!=D)
print(A==B==C==D)
print(A!=B>=C<=D)
print(A==B<=C>=D)
print(A!=B>=C<=D)
print(A==B<=C>=D)
print(A!=B<=C!=D)
print(A==B>=C==D)
print(A!=B<=C!=D)
print(A==B>=C==D)
print(A!=B!=C==D)
print(A==B==C!=D)       
print(A!=B==C!=D)
print(A==B!=C==D)
print(A!=B==C==D)
print(A!=B!=C==D)
print(A==B==C!=D)
print(A!=B==C!=D)
print(A==B!=C==D)
print(A!=B!=C!=D)
print(A==B==C==D)
print(A<B<C<D)
print(A>B>C>D)
print(A<B>C<D)
print(A>B<C>D)
print(A==B<C!=D)
print(A!=B>C==D)
print(A==B<C!=D) 
print(A!=B>C==D)
print(A==B<=C!=D)
print(A!=B>=C==D)
print(A==B<=C!=D)
print(A!=B>=C==D)
#  